### ISSUE TITLE
Default for Spline

### ISSUE THREAD

**Issue by perlindgren** [phaazon/splines#101]
Hi folks.

Great library, I use it with Egui to good effect, for modelling curves.

I'm using `serde` but want the actual spline not to be serialized as I store only the knots in my own data structure.

To that end I want to use `#[serde(skip)]` but as I understand it requires `Default` to be implemented for the data structure.

I added an implementation per: https://github.com/phaazon/splines/pull/100

It passes all test so should be safe to merge.

/Per

**Comment by phaazon** [comment]
This is now released as part of [splines-4.3.1](https://crates.io/crates/splines/4.3.1).
