### ISSUE TITLE
Interpolation between 64 bit values

### ISSUE THREAD

**Issue by Frederik-Baetens** [phaazon/splines#12]
Would it be hard to add interpolation between f64 values? It seems like it's just implementing one trait for it. If you think it would be easy to port the f32 impl to f64, I'd gladly take a look at it.

**Comment by phaazon** [comment]
No it wouldn’t!

**Comment by phaazon** [comment]
I’m currently on it.

**Comment by phaazon** [comment]
Fixed. Will be part of `splines-1.0.0-rc.1`.
