### ISSUE TITLE
Support for nalgebra

### ISSUE THREAD

**Issue by nsmryan** [phaazon/splines#5]
I have been playing around with the ggez crate, which uses nalgebra instead of cgmath, and I was wondering if you would accept a pull request adding an "impl-nalgebra" feature to splines with interpolation for nalgebra's Point and Vector.

I looked at what this would require, and too be honest I don't really understand how the cgmath impls work in the splines code, as their implementation of lerp is just self.lerp, rather than lerping the components of the given structs.

Thank you

**Comment by phaazon** [comment]
For sure I would accept it! The `lerp` stuff is a bit misunderstanding (maybe I should change the name): it uses the `self` version from cgmath but the `lerp` defined in the `Interpolate` trait is a static method.

**Comment by nsmryan** [comment]
That makes perfect sense- I'm still new to Rust and didn't make that distinction.

I have an implementation of the nalgebra Point and Matrix type which covers all the Vector types as well (which are type alias for Matrix). The trait bounds are somewhat complex for Matrix, and I don't entirely understand them to be honest, so I was hoping to simplify them or just provide more straightforward implementations for a limited set of types instead of trying to be so generic.

One thing I'm not familiar with is travis integration. I imagine there should be a line to build and test with the impl-nalgebra feature, but I'm not sure how to test that the change works.

**Comment by phaazon** [comment]
If you think it’s too hard for `Matrix`, we can ship the features for `Vector` first and just add the matrix in a minor bump afterwards.

I’ll come back to you for the CI stuff, it’s really messy and I don’t know (yet) the optimal solution for that.
