### ISSUE TITLE
`clamped_sample` panics if there are not enough points for Catmull-Rom interpolation.

### ISSUE THREAD

**Issue by MichaelMauderer** [phaazon/splines#9]
This is not documented in the `clamped_sample` docstring. It might be even better if there was a more graceful fallback (e.g., returning an option).

**Comment by phaazon** [comment]
Yep, I think all panics should be removed from the current public interface. Thanks for pointing out!

**Comment by Frederik-Baetens** [comment]
I think this is related: it only panics when the parameter is too big, when there are not enough points to the left, it just returns the leftmost point.

**Comment by phaazon** [comment]
Fixed. Will be part of `splines-1.0.0-rc.1`.
